name: Android CI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:

  build-release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease && mv app/build/outputs/apk/release/*.apk app/androidthemestore.apk

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidIDE-Theme-Store-Release
          path: app/androidthemestore-release.apk
